[custom]

ruleset=HOME,[]IP-CIDR,192.168.5.0/24
;1、全面换回 100% 兼容的文本（.list）规则集，彻底告别二进制解析失败
; 👽︎ AI 策略
ruleset=👽︎ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/AI.list
ruleset=👽︎ AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list

; 👨🏿‍💻 GitHub 策略
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list

; 🎧︎ TikTok 策略
ruleset=🎧︎ TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list

; 📺 油管 策略
ruleset=📺 油管,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list

; 📹︎ NETFLIX 策略
ruleset=📹︎ NETFLIX,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list

; 👑 迪士尼 策略
ruleset=👑 迪士尼,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list

; 🎮︎ steam 游戏策略 (包含主平台、任天堂、Epic、EA)
ruleset=🎮︎ steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮︎ steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Nintendo.list
ruleset=🎮︎ steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮︎ steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list

; 🪟 Microsoft 策略
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list

; 🍎 Apple 策略
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

; 📲 Telegram 策略
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list

; 🌍 国外媒体 策略
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list

; 🚀 默认代理 策略 (非华语全球大类、Google大类、PayPal、测速、GFW及个人自定义Proxy)
ruleset=🚀 默认代理,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/Proxy.list
ruleset=🚀 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
ruleset=🚀 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🚀 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
ruleset=🚀 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list

; 🎯 直连 策略 (全量广告拦截、局域网、国内域名、国内媒体及国内 IP 兜底)
ruleset=🎯 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 直连,[]GEOIP,CN

; 🐠 漏网之鱼 策略
ruleset=🐠 漏网之鱼,[]FINAL


;2、正式展示在 Clash 里的高级 ⚙️ 业务策略组
custom_proxy_group=🚀 默认代理`select`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=📺 油管`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=👽︎ AI`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🎮︎ steam`select`[]🎯 直连`[]🚀 默认代理`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=📲 Telegram`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🎧︎ TikTok`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=📹︎ NETFLIX`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=👑 迪士尼`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🪟 Microsoft`select`[]🎯 直连`[]🚀 默认代理`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🍎 Apple`select`[]🎯 直连`[]🚀 默认代理`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🎯 直连`select`[]DIRECT
custom_proxy_group=🐠 漏网之鱼`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]♻️ 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=HOME`select`[]🚀 默认代理`[]🎯 直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]♻️ 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点

; 全局兜底自动与全部节点
custom_proxy_group=👻 自动选择`url-test`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连官网|距离|更新|订阅|网站|流量|时间|到期|直连)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐶 全部节点`select`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连)).)*$


;3、基础静态节点提取
custom_proxy_group=🇭🇰 香港节点`select`(?i)港|🇭🇰|hk|hongkong|hong kong
custom_proxy_group=🇨🇳 台湾节点`select`台|(?i)湾|🇹🇼|🇨🇳
custom_proxy_group=🇯🇵 日本节点`select`(?i)日|jp|🇯🇵|japan
custom_proxy_group=🇸🇬 狮城节点`select`(?i)新加坡|坡|狮城|🇸🇬|SG|Singapore
custom_proxy_group=🇺🇲 美国节点`select`(?i)美|🇺🇸|🇺🇲|unitedstates|united states
custom_proxy_group=☠️ 他国节点`select`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连官网|距离|更新|订阅|网站|流量|时间|到期|直连|美|🇺🇸|🇺🇲|港|🇭🇰|台|🇹🇼|🇨🇳|日|🇯🇵|新|🇸🇬)).)*$


;4、🔯 故障转移容灾组
custom_proxy_group=🔯 香港故转`fallback`[]🇭🇰 香港节点`[]♻️ 香港智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 台湾故转`fallback`[]🇨🇳 台湾节点`[]♻️ 台湾智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 日本故转`fallback`[]🇯🇵 日本节点`[]♻️ 日本智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 狮城故转`fallback`[]🇸🇬 狮城节点`[]♻️ 狮城智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 美国故转`fallback`[]🇺🇲 美国节点`[]♻️ 美国智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 他国故转`fallback`[]☠️ 他国节点`[]♻️ 他国智能`http://www.gstatic.com/generate_204`180


;5、♻️ 智能测速组
custom_proxy_group=♻️ 香港智能`url-test`(?=.*(港|🇭🇰|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 台湾智能`url-test`(?=.*(台|(?i)湾|🇹🇼|🇨🇳))^((?!(日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 日本智能`url-test`(?=.*(日|🇯🇵|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 狮城智能`url-test`(?=.*(新加坡|🇸🇬|(?i)坡|狮城|SG|Singapore))^((?!(港|台|韩|日|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 美国智能`url-test`(?=.*(美|🇺🇸|🇺🇲|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 他国智能`url-test`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连官网|距离|更新|订阅|网站|流量|时间|到期|直连|美|🇺🇸|🇺🇲|港|🇭🇰|台|🇹🇼|🇨🇳|日|🇯🇵|新|🇸🇬)).)*$`http://www.gstatic.com/generate_204`600,,50


enable_rule_generator=true
overwrite_original_rules=true
