Ini, TOML
[custom]

;1、高性能规则集定义（全面参照 OpenClash 最新 MRS 路径）
ruleset=fakeipfilter_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-all.mrs
ruleset=private_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/private.mrs
ruleset=proxylite_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/geolocation-!cn.mrs
ruleset=ai_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ai-!cn.mrs
ruleset=youtube_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/youtube.mrs
ruleset=google_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google.mrs
ruleset=steam_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/steam.mrs
ruleset=Nintendo_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/nintendo.yaml
ruleset=Epic_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/epicgames.mrs
ruleset=Origin_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/ea.mrs
ruleset=github_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/github.mrs
ruleset=telegram_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/telegram.mrs
ruleset=netflix_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/netflix.mrs
ruleset=disney_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/disney.mrs
ruleset=paypal_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/paypal.mrs
ruleset=onedrive_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/onedrive.mrs
ruleset=microsoft_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/microsoft.mrs
ruleset=apple_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/apple.mrs
ruleset=speedtest_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/ookla-speedtest.mrs
ruleset=tiktok_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/tiktok.mrs
ruleset=gfw_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/gfw.mrs
ruleset=cn_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/cn.mrs
ruleset=cnm_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-media-cn.mrs
ruleset=video_domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-social-media-!cn.mrs

; IP类规则
ruleset=private_ip,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/private.mrs
ruleset=cn_ip,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/cn.mrs
ruleset=google_ip,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/google.mrs
ruleset=telegram_ip,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/telegram.mrs
ruleset=netflix_ip,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/netflix.mrs
ruleset=apple_ip,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta-lite/geoip/apple.mrs


;2、出站策略组 (1:1 像素级复制 OpenClash 核心逻辑与名字)
custom_proxy_group=🚀 默认代理`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=📺 油管`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🌍 国外媒体`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🪅 Google`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=👽︎ AI`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=👨🏿‍💻 GitHub`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🐬 OneDrive`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🎧︎ TikTok`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=📲 Telegram`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=📹︎ NETFLIX`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=👑 迪士尼`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🎮︎ steam`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=✈️ Speedtest`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=💶 PayPal`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🍎 Apple`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🪟 Microsoft`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🎯 直连`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点
custom_proxy_group=🐠 漏网之鱼`select`[]直连`[]👻 自动选择`[]♻️ 香港智能`[]♻️ 台湾智能`[]♻️ 日本智能`[]♻️ 狮城智能`[]♻️ 美国智能`[]♻️ 他国智能`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 日本故转`[]🔯 狮城故转`[]🔯 美国故转`[]🔯 他国故转`[]🐶 全部节点


;3、基础节点筛选区域（利用正则提取对应区域节点）
custom_proxy_group=🇭🇰 香港节点`select`(?i)港|🇭🇰|hk|hongkong|hong kong
custom_proxy_group=🇨🇳 台湾节点`select`台|(?i)湾|🇹🇼|🇨🇳
custom_proxy_group=🇯🇵 日本节点`select`(?i)日|jp|🇯🇵|japan
custom_proxy_group=🇸🇬 狮城节点`select`(?i)新加坡|坡|狮城|🇸🇬|SG|Singapore
custom_proxy_group=🇺🇲 美国节点`select`(?i)美|🇺🇸|🇺🇲|unitedstates|united states
custom_proxy_group=☠️ 他国节点`select`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连官网|距离|更新|订阅|网站|流量|时间|到期|直连|美|🇺🇸|🇺🇲|港|🇭🇰|台|🇹🇼|🇨🇳|日|🇯🇵|新|🇸🇬)).)*$


;4、🔯 故障转移故转组 (实现 Fallback 塌陷救场逻辑)
custom_proxy_group=🔯 香港故转`fallback`[]🇭🇰 香港节点`[]♻️ 香港智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 台湾故转`fallback`[]🇨🇳 台湾节点`[]♻️ 台湾智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 日本故转`fallback`[]🇯🇵 日本节点`[]♻️ 日本智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 狮城故转`fallback`[]🇸🇬 狮城节点`[]♻️ 狮城智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 美国故转`fallback`[]🇺🇲 美国节点`[]♻️ 美国智能`http://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 他国故转`fallback`[]☠️ 他国节点`[]♻️ 他国智能`http://www.gstatic.com/generate_204`180


;5、♻️ 智能测速组 (包含排除特定节点的进阶正则)
custom_proxy_group=♻️ 香港智能`url-test`(?=.*(港|🇭🇰|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 台湾智能`url-test`(?=.*(台|(?i)湾|🇹🇼|🇨🇳))^((?!(日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 日本智能`url-test`(?=.*(日|🇯🇵|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 狮城智能`url-test`(?=.*(新加坡|🇸🇬|(?i)坡|狮城|SG|Singapore))^((?!(港|台|韩|日|美)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 美国智能`url-test`(?=.*(美|🇺🇸|🇺🇲|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=♻️ 他国智能`url-test`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连官网|距离|更新|订阅|网站|流量|时间|到期|直连|美|🇺🇸|🇺🇲|港|🇭🇰|台|🇹🇼|🇨🇳|日|🇯🇵|新|🇸🇬)).)*$`http://www.gstatic.com/generate_204`600,,50

; 全局兜底自动与全部节点
custom_proxy_group=👻 自动选择`url-test`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连官网|距离|更新|订阅|网站|流量|时间|到期|直连)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐶 全部节点`select`^((?!(套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|官网|距离|更新|订阅|网站|流量|时间|到期|直连)).)*$


;6、规则绑定路由映射（与分流组无缝衔接）
; 特殊单品规则映射
ruleset=ai_domain,👽︎ AI
ruleset=github_domain,👨🏿‍💻 GitHub
ruleset=youtube_domain,📺 油管
ruleset=steam_domain,🎮︎ steam
ruleset=Nintendo_domain,🎮︎ steam
ruleset=Epic_domain,🎮︎ steam
ruleset=Origin_domain,🎮︎ steam
ruleset=google_domain,🪅 Google
ruleset=onedrive_domain,🐬 OneDrive
ruleset=microsoft_domain,🪟 Microsoft
ruleset=apple_domain,🍎 Apple
ruleset=tiktok_domain,🎧︎ TikTok
ruleset=telegram_domain,📲 Telegram
ruleset=speedtest_domain,✈️ Speedtest
ruleset=netflix_domain,📹︎ NETFLIX
ruleset=disney_domain,👑 迪士尼
ruleset=paypal_domain,💶 PayPal

; IP类匹配
ruleset=apple_ip,🍎 Apple
ruleset=google_ip,🪅 Google
ruleset=netflix_ip,📹︎ NETFLIX
ruleset=telegram_ip,📲 Telegram

; 媒体与兜底大类
ruleset=video_domain,🌍 国外媒体
ruleset=gfw_domain,🚀 默认代理
ruleset=proxylite_domain,🚀 默认代理

; 国内流量直连
ruleset=cn_domain,🎯 直连
ruleset=cnm_domain,🎯 直连
ruleset=cn_ip,🎯 直连
ruleset=➡️ 国内,[]GEOIP,CN

; 终极兜底
ruleset=🐠 漏网之鱼,[]FINAL

enable_rule_generator=true
overwrite_original_rules=true
